### ISSUE TITLE
Help widget covers x on full screen modals

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-lib-help#12]
When a full screen modal is opened the button for the help widget flyout covers the modal's x in its header. 

Note: This may be a sky 2 issue but that should be verified before moving this issue to that repository.

**Comment by Blackbaud-BrandonJones** [comment]
![screen shot 2017-10-06 at 9 48 09 am](https://user-images.githubusercontent.com/20796436/31281237-d96f99da-aa7c-11e7-86bc-cf171b999bd9.png)

**Comment by Blackbaud-BrandonJones** [comment]
Resolved with the following PRs:
https://github.com/blackbaud/skyux2/pull/1214
and 
https://github.com/blackbaud/skyux-builder/pull/301
