### ISSUE TITLE
Issue reported to K-12 Core team for Bug Triage, reproduced in RE NXT

### ISSUE THREAD

**Issue by Blackbaud-BrynaGleich** [blackbaud/skyux-lib-help#23]
Bug notes are here, but issue can be reproduced in RE NXT

https://blackbaud.visualstudio.com/Products/K12%20-%20T3B/_workitems?_a=edit&id=855396

**Comment by Blackbaud-LindseyRix** [comment]
Chat and Case Central links are failing to open in Chat.

**Comment by Blackbaud-BrandonJones** [comment]
Resolved with config updates
