### ISSUE TITLE
Ability to hide Help on specific pages/routes in SPA

### ISSUE THREAD

**Issue by Blackbaud-PeteLukich** [blackbaud/skyux-lib-help#27]
i have some special pages in my SPA that are not user-interactive pages.  i want to hide the green Help icon on these pages.  i'm hoping for some easy directive i can add to those pages like `<bb-help disable="true"/>`

**Comment by Blackbaud-BrandonJones** [comment]
Resolved with release 1.2.0 and will be available in the next version of Skyux Builder.

https://github.com/blackbaud/skyux-lib-help/pull/31
