### ISSUE TITLE
3 scrollbars in Help widget

### ISSUE THREAD

**Issue by Blackbaud-RoxAnnaFuquay** [blackbaud/skyux-lib-help#35]
When I undock the Help widget in one of the cdev environments, there are 3 scrollbars.

**Comment by Blackbaud-BrandonJones** [comment]
Image for reference.
![image 3](https://user-images.githubusercontent.com/20796436/41729501-5ac96796-7547-11e8-96e2-2b38d0384617.png)

**Comment by Blackbaud-LindseyRix** [comment]
Researched determined most of the scrollbars were coming from Flare. If this continues to be an issue, please re-open this issue.
